# Standardkonfiguration des Q9-Treibers.
# Weitere [target.NAME]-Sektionen können später ergänzt werden.
[global]
target=OS9-68K
frontend=c
qcpp=../Q9-FRONTEND-C/q9-qcpp/build/qcpp
qcir=../Q9-FRONTEND-C/q9-qcir/build/qcir

[target.OS9-68K]
cpu=68000
backend=../Q9-BACKEND-68K/q9-qir68k/build/qir68k
optimizer=../Q9-BACKEND-68K/q9-qo68k/build/qo68k
assembler=../Q9-BACKEND-68K/q9-qr68k/build/qr68k
linker=../Q9-BACKEND-68K/q9-ql68k/build/ql68k
startup=cstart.a
libraries=clib.l,os9.l,sys.l
