# Standardkonfiguration des Q9-Treibers.
# Weitere [target.NAME]-Sektionen können später ergänzt werden.
[global]
target=OS9-68K
frontend=c
qcpp=../Q9-FRONTEND-C/q9-qcpp/build/qcpp
qcir=../Q9-FRONTEND-C/q9-qcir/build/qcir

[target.OS9-68K]
cpu=68000
backend=qir68k
optimizer=qo68k
assembler=qr68k
linker=ql68k
startup=cstart.a
libraries=clib.l,os9.l,sys.l
